### ISSUE TITLE
No success with tokeninfo

### ISSUE THREAD

**Issue by beatrubi** [bolkedebruin/rdpgw#106]
I manged to pass a user token from rdpgw through xrdp with [enable_token_login=true](https://github.com/neutrinolabs/xrdp/pull/1668) and [pam-jwt](https://github.com/bolkedebruin/pam-jwt) back to rdpgw.

The generated rdp file contains the username with concatenated token:
```
gatewayhostname:s:rdpgw.lab.0x1b.ch:8443
full address:s:ubuntu03.lab.0x1b.ch:3389
username:s:beat^_eyJhbGciOiJkaXIiLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiemlwIjoiREVGIn0..kyekj2rYsFoUl781IkGG0w.x8vf2eBx_szYtYGfuYjtoTD33DBUENzvhPRjAWaho7zZw1BVgXjyPnmqkqiZdAbuBTMKuwN6YIGDsiN1gvIzLQ.b82or-ul-bCkDmtvUVMmbg
gatewaycredentialssource:i:5
gatewayprofileusagemethod:i:1
gatewayusagemethod:i:1
...
```
`xrdp-sesman` successfully calls the PAM module:
```
Apr 11 20:28:05 ubuntu03 xrdp[8765]: [INFO ] sending login info to session manager, please wait...
Apr 11 20:28:05 ubuntu03 pam-jwt[8613]: token url set to https://rdpgw.lab.0x1b.ch:8443/tokeninfo?access_token
```
According to `rdpgw`'s log I get the identical token back to validate - sadly no success:
```
Apr 11 20:28:05 rdpgw.lab.0x1b.ch docker[9665]: rdpgw  | 2024/04/11 18:28:05 Identity SessionId: b74ac558-9a75-40ab-a611-18a73ad09964, UserName: : Authenticated: false: Path: /tokeninfo?access_token=eyJhbGciOiJkaXIiLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiemlwIjoiREVGIn0..kyekj2rYsFoUl781IkGG0w.x8vf2eBx_szYtYGfuYjtoTD33DBUENzvhPRjAWaho7zZw1BVgXjyPnmqkqiZdAbuBTMKuwN6YIGDsiN1gvIzLQ.b82or-ul-bCkDmtvUVMmbg
Apr 11 20:28:05 rdpgw.lab.0x1b.ch docker[9665]: rdpgw  | 2024/04/11 18:28:05 Cannot decrypt token go-jose/go-jose: missing payload in JWS message
```
Now I'm lost, the encoder and decoder for the user token goes beyond my Go skills 😬  I'm not sure if I screwed something up or if the code to encode and decode the limited JWT do not match.

For completeness my `rdpgw.conf`:
```yaml
Server:
 CertFile: /opt/rdpgw/server.pem
 KeyFile: /opt/rdpgw/key.pem
 GatewayAddress: rdpgw.lab.0x1b.ch:8443
 Port: 8443
 Hosts:
  - ubuntu01.lab.0x1b.ch:3389
  - ubuntu02.lab.0x1b.ch:3389
  - ubuntu03.lab.0x1b.ch:3389
 HostSelection: unsigned
 SessionKey: d505d0d5ce23977b9d544e224692f77d
 SessionEncryptionKey: f088998ac5b017a2593f211a8ce39ca9
OpenId:
 ProviderUrl: https://rdpgw.lab.0x1b.ch/auth/realms/demo
 ClientId: rdpgw
 ClientSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Client:
 UsernameTemplate: "{{ username }}\x1f{{ token }}"
 NetworkAutoDetect: 0
 BandwidthAutoDetect: 1
 ConnectionType: 6
Security:
  PAATokenSigningKey: fc4c2095bc3409375461bc9ef36f7b89
  PAATokenEncryptionKey: 8188742ac3cf0efe67805a9797d2a349
  UserTokenEncryptionKey: d3ecd7e565e56e37e2f2e95b584d8c0c
  UserTokenSigningKey: 5aa3a1568fe8421cd7e127d5ace28d2d
  VerifyClientIp: true
  EnableUserToken: true
Caps:
 TokenAuth: true
```
