### ISSUE TITLE
OIDC / AzureAD error: "securecookie: the value is too long"

### ISSUE THREAD

**Issue by sphr2k** [bolkedebruin/rdpgw#15]
Very interesting project - thought I'd give this a try.

* Compiled master (`3919a7e`)
* Configured to use Azure AD for OIDC auth
* Getting the following error after successful authentication:
  ```securecookie: the value is too long```
* The service logs this:
   ```2021/02/24 18:46:51 http: superfluous response.WriteHeader call from github.com/bolkedebruin/rdpgw/api.(*Config).HandleCallback (web.go:118)```

Any idea? Is there a flag to get more debug output?

Thanks :)

**Comment by bolkedebruin** [comment]
The issue is that Azure OIDC probably returns a lot of information in the idtoken. By default this token gets stored in the cookie. This makes the gateway stateless. 

It is is possible to configure a different store for this however I don't think I made this configurable so it would require a patch. And again that would make the gateway require a backend like a filesystem or a database. A better workaround would be to limit what Azure OIDC returns.

**Comment by sphr2k** [comment]
Thanks for your reply. I don't think it ist possible to configure this in Azure AD, but i'll take a look.

**Comment by jH-** [comment]
@sphr2k Did you look into a workaround for this issue? Currently stuck in the same scenario.

**Comment by sphr2k** [comment]
Sorry, no, didn't pursue this. Maybe you coule try to put Dex in between?

**Comment by bolkedebruin** [comment]
@jH- you can now configure (rdpgw from master) the gateway to use a filesystem store instead of a cookie store for sessions. This should remove this issue at the expense of needing to keep clients connected to the same rdpgw instance during the exchange of credentials. This is typically the case with load balancers, but ymmv. See the rdpgw.yaml template on how to configure this. Let me know if this works for you

**Comment by jH-** [comment]
@bolkedebruin Thank you, I'll have a go at

**Comment by sphr2k** [comment]
@bolkedebruin I tried again w/ Azure AD. Getting the following errors:

Web browser:
```
securecookie: error - caused by: crypto/aes: invalid key size 33
```

Server_
```
2022/08/14 18:40:23 http: superfluous response.WriteHeader call from github.com/bolkedebruin/rdpgw/cmd/rdpgw/api.(*Config).HandleCallback (web.go:126)
2022/08/14 18:41:15 http: superfluous response.WriteHeader call from github.com/bolkedebruin/rdpgw/cmd/rdpgw/api.(*Config).HandleCallback (web.go:126)
```

**Comment by sphr2k** [comment]
I also tried with Dex as the IDP and and a minimal config - getting the same error.

Here's the Dex config

```yaml
issuer: https://dex.tld.com

storage:
  type: sqlite3
  config:
    file: /data/dex.db

web:
  http: 127.0.0.1:5556

telemetry:
  http: 127.0.0.1:5558

grpc:
  addr: 127.0.0.1:5557

staticClients:
  - id: rdpgw
    redirectURIs:
      - 'https://rdpgw.tld.com/callback'
    name: 'RDP Gateway'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

connectors:
  - type: mockCallback
    id: mock
    name: Example

enablePasswordDB: true

staticPasswords:
  - email: "some@user.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```
