### ISSUE TITLE
Use local auth

### ISSUE THREAD

**Issue by archef2000** [bolkedebruin/rdpgw#62]
Hello im trying to setup rdpgw via docker trough the provided docker-compose.yaml. My issue is that there is no documentation. And if i try to run rdpgw-auth with sh, exec or entrypoint it fails to start with the error message "file or directory not found" but the provided file path exists i can even confirm the file exists via cat even tough it is unreadable because it is a binary.

**Comment by bolkedebruin** [comment]
rdpgw-auth needs to have PAM available inside the container and, therefore, needs to run as root. Another option is to have `sssd` available inside the container. root is then not required. Explaining how to set that up please refer to `sssd` documentation.

`sh` is not available inside the standard container and if using entrypoint you need to be careful in setting it up `["/opt/bin/rdpgw-auth"]`.

**Comment by Archef2000** [comment]
I run it as root in a debian docker container that has a user called abc with a password setup

**Comment by bolkedebruin** [comment]
I suggest debugging your PAM setup first with a container that runs SSH (with PAM turned on) or something alike. Logs from /var/log/ can be helpful as is your Dockerfile.

**Comment by Archef2000** [comment]
I run this 
```bash
useradd -c "abc" -m abc
echo "abc:abc" | chpasswd

cat <<EOT > rdpgw.yaml
Server:
 Authentication:
  - local
 AuthSocket: /tmp/rdpgw-auth.sock
 Tls: auto
 CertFile: /opt/rdpgw/server.pem
 KeyFile: /opt/rdpgw/key.pem
 GatewayAddress: host.tld
 Port: 9443
 Hosts:
  - xrdp:3389
 HostSelection: roundrobin
 SessionKey: amgRRTziC8iDB5L1LgsheFsREUyRVsjS
 SessionEncryptionKey: xQxWCFNNpyopnj6a8Fdn0fir21ps2IRD
 SessionStore: cookie
Caps:
 SmartCardAuth: false
 TokenAuth: false
 IdleTimeout: 10000
 EnablePrinter: true
 EnablePort: true
 EnablePnp: true
 EnableDrive: true
 EnableClipboard: true
Client:
  UsernameTemplate: "{{ username }}\x1f{{ token }}"
  NetworkAutoDetect: 0
  BandwidthAutoDetect: 1
  ConnectionType: 6
  SplitUserDomain: false
Security:
  PAATokenSigningKey: PH2aVB2Rdu1ed2obu30KRTJFAcR3c0VC
  PAATokenEncryptionKey: 5pwGjt2wf3yGs6M4D0TzyFwW48LSz7Y8
  UserTokenEncryptionKey: MKoXaLdeCJ4458QE51yLGDjfSARhvpPq
  EnableUserToken: false
  VerifyClientIp: true
EOT

exec ./rdpgw-auth &
exec ./rdpgw 
```
inside `archef2000/rdpgw` but it is privileged and has `sleep 999d` as command and i then exec inside the container

**Comment by archef2000** [comment]
Could you may share a full example of a local setup

**Comment by archef2000** [comment]
ssh pam setup is working i also set it up on bare metal ubuntu with the same config file but not working

**Comment by bolkedebruin** [comment]
Please share config (docker pam) and logs (rdp, auth, pam). This isn't much to go on, unfortunately.

**Comment by archef2000** [comment]
Sorry for taking a lot of time to answer.
* I have a LE cert for a subdomain
* i have mounted
```
      -~/rdpgw.yaml:/opt/rdpgw/rdpgw.yaml:ro
      - ~/privkey.pem:/opt/rdpgw/key.pem:ro
      - ~/fullchain.pem:/opt/rdpgw/server.pem:ro
      - /etc/pam.d/:/etc/pam.d/
      - /etc/shadows:/etc/shadows:ro
      - /etc/passwd:/etc/passwd:ro
```
* otherwise i use `archef2000/rdpgw:debian` as docker image but have also tried it on bare metal
* I use the default windows client to connect to `lscr.io/linuxserver/rdesktop:ubuntu-xfce`

My config:
```yaml
Server:
 Authentication:
  - local
 AuthSocket: /tmp/rdpgw-auth.sock
 Tls: true
 CertFile: /opt/rdpgw/server.pem
 KeyFile: /opt/rdpgw/key.pem
 GatewayAddress: rdp.domain.tld
 Port: 9443
 Hosts:
  - xrdp:3389
 HostSelection: roundrobin
 SessionKey: secret
 SessionEncryptionKey: secret
 SessionStore: cookie
Caps:
 SmartCardAuth: false
 TokenAuth: false
 IdleTimeout: 10
 EnablePrinter: true
 EnablePort: true
 EnablePnp: true
 EnableDrive: true
 EnableClipboard: true
Client:
  UsernameTemplate: "{{ username }}\x1f{{ token }}"
  NetworkAutoDetect: 0
  BandwidthAutoDetect: 1
  ConnectionType: 6
  SplitUserDomain: false
Security:
  PAATokenSigningKey: secret
  PAATokenEncryptionKey: secret
  UserTokenEncryptionKey: secret
  EnableUserToken: false
  VerifyClientIp: false
```
